---
title             : "Entity Matching for Online Marketplace: Applying Text Embeddings and Deep Learning to Product Matching"
shorttitle        : "Entity Matching for Online Marketplace"

author: 
  - name          : "Kyle Gilde"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Chicago, IL"
    email         : "kylegilde@gmail.com"

affiliation:
  - id            : "1"
    institution   : | 
                      Master of Science in Data Science
                      
                      Capstone Project
                      
                      City University of New York
                      


abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["/Users/kyleg/Entity-Matching-in-Online-Retail/bibliography.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")

```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->



# Results

# Discussion


\newpage

# References
```{r create_bibliography}
r_refs(file = "/Users/kyleg/Entity-Matching-in-Online-Retail/bibliography.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
